-- ============================================================
-- Vague 6 : journal des connexions + administrateur principal
-- À exécuter dans Supabase > SQL Editor APRÈS securite.sql.
-- Relançable sans risque.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Administrateur principal
-- ------------------------------------------------------------
alter table admin_users add column if not exists is_owner boolean not null default false;

-- S'il n'y a encore aucun administrateur principal, le plus ancien le devient.
-- Pour choisir un autre compte :
--   update admin_users set is_owner = true
--   where id = (select id from auth.users where email = 'ton-email@exemple.com');
update admin_users set is_owner = true
where id = (select id from admin_users order by created_at limit 1)
  and not exists (select 1 from admin_users where is_owner);

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from admin_users where id = auth.uid() and is_owner);
$$;
grant execute on function public.is_owner() to authenticated;

-- Seul l'administrateur principal peut ajouter, modifier ou retirer des admins.
-- (Avant : n'importe quel admin pouvait retirer les droits des autres.)
drop policy if exists hm_admin_all   on admin_users;
drop policy if exists hm_admin_read  on admin_users;
drop policy if exists hm_owner_write on admin_users;
drop policy if exists hm_owner_update on admin_users;
drop policy if exists hm_owner_delete on admin_users;

create policy hm_admin_read   on admin_users for select to authenticated using (public.is_admin());
create policy hm_owner_write  on admin_users for insert to authenticated with check (public.is_owner());
create policy hm_owner_update on admin_users for update to authenticated using (public.is_owner()) with check (public.is_owner());
create policy hm_owner_delete on admin_users for delete to authenticated using (public.is_owner());

-- Interdit de supprimer ou rétrograder le DERNIER administrateur principal.
create or replace function public.keep_one_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.is_owner
     and (tg_op = 'DELETE' or not new.is_owner)
     and not exists (select 1 from admin_users where is_owner and id <> old.id) then
    raise exception 'last_owner';
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists admin_users_keep_owner on admin_users;
create trigger admin_users_keep_owner
  before update or delete on admin_users
  for each row execute function public.keep_one_owner();


-- ------------------------------------------------------------
-- 2. Journal des tentatives de connexion
-- ------------------------------------------------------------
-- Rempli UNIQUEMENT par le serveur du site (clé secrète service_role) :
-- un visiteur ne peut ni écrire, ni lire, ni effacer ce journal.
create table if not exists login_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text,
  ip text,
  country text,
  user_agent text,
  success boolean not null default false,
  -- success | bad_password | not_admin | blocked | invalid
  reason text
);

create index if not exists login_attempts_created_idx on login_attempts (created_at desc);
create index if not exists login_attempts_ip_idx      on login_attempts (ip, created_at desc);
create index if not exists login_attempts_email_idx   on login_attempts (lower(email), created_at desc);

alter table login_attempts enable row level security;
drop policy if exists hm_owner_read on login_attempts;
create policy hm_owner_read on login_attempts for select to authenticated using (public.is_owner());
-- Aucune règle d'écriture : seul le serveur (service_role) peut ajouter des lignes.

-- Protection des données personnelles : on garde 90 jours d'historique.
create or replace function public.purge_old_login_attempts()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from login_attempts where created_at < now() - interval '90 days';
  return null;
end;
$$;

drop trigger if exists login_attempts_purge on login_attempts;
create trigger login_attempts_purge
  after insert on login_attempts
  for each statement execute function public.purge_old_login_attempts();


-- ------------------------------------------------------------
-- 3. Événements du système de connexion Supabase
-- ------------------------------------------------------------
-- Montre aussi les connexions faites directement auprès de Supabase,
-- sans passer par le formulaire du site. Réservé à l'administrateur principal.
create or replace function public.admin_auth_events(p_limit integer default 100)
returns table (created_at timestamptz, action text, email text, ip text)
language plpgsql
stable
security definer
set search_path = public, auth
as $$
begin
  if not public.is_owner() then
    raise exception 'forbidden';
  end if;

  return query
    select e.created_at,
           e.payload->>'action',
           coalesce(e.payload->>'actor_username', e.payload->'traits'->>'user_email'),
           e.ip_address::text
    from auth.audit_log_entries e
    where e.payload->>'action' <> 'token_refreshed'
    order by e.created_at desc
    limit least(greatest(p_limit, 1), 500);
end;
$$;

revoke all on function public.admin_auth_events(integer) from public;
grant execute on function public.admin_auth_events(integer) to authenticated;
