-- ============================================================
-- Vague 5 : SÉCURITÉ (Row Level Security)
-- À exécuter UNE fois dans Supabase > SQL Editor, après i18n-english.sql,
-- et EN MÊME TEMPS que la mise à jour du code (les commandes, le suivi et
-- les codes promo passent désormais par les fonctions ci-dessous).
-- Le script peut être relancé sans risque.
-- Version 2 : moyen de paiement, statut « payé », limite anti-spam,
-- suppression des fonctions de stock ouvertes au public.
--
-- Principe :
--   • Visiteurs : lecture du catalogue publié uniquement.
--   • Commandes, suivi, codes promo : uniquement via des fonctions serveur
--     qui recalculent les prix et vérifient le stock.
--   • Administrateurs (table admin_users) : accès complet.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Qui est administrateur ?
-- ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from admin_users where id = auth.uid());
$$;


-- ------------------------------------------------------------
-- 2. Colonnes utiles
-- ------------------------------------------------------------
-- Numéro de commande court, à communiquer au client pour le suivi.
alter table orders add column if not exists order_number bigint generated by default as identity;
create unique index if not exists orders_order_number_idx on orders (order_number);

-- Moyen de paiement choisi par le client et suivi du paiement par l'admin.
alter table orders add column if not exists payment_method text not null default 'cash';
alter table orders add column if not exists paid boolean not null default false;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'orders_payment_method_check') then
    alter table orders add constraint orders_payment_method_check
      check (payment_method in ('mtn_momo', 'moov_money', 'celtiis_cash', 'cash'));
  end if;
end $$;
create index if not exists orders_created_at_idx on orders (created_at);

-- Les avis ne sont plus publiés automatiquement : validation dans l'admin.
alter table product_reviews alter column approved set default false;


-- ------------------------------------------------------------
-- 3. Activer la sécurité sur toutes les tables
-- ------------------------------------------------------------
alter table categories      enable row level security;
alter table products        enable row level security;
alter table product_images  enable row level security;
alter table orders          enable row level security;
alter table order_items     enable row level security;
alter table admin_users     enable row level security;
alter table product_reviews enable row level security;
alter table promo_codes     enable row level security;
alter table blog_posts      enable row level security;
alter table bundles         enable row level security;
alter table bundle_items    enable row level security;
alter table social_posts    enable row level security;


-- ------------------------------------------------------------
-- 4. Règles d'accès
-- ------------------------------------------------------------
-- On supprime d'abord les règles de ce script (pour pouvoir le relancer).
do $$
declare r record;
begin
  for r in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and policyname like 'hm_%'
  loop
    execute format('drop policy %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

-- Administrateurs : tout est permis sur toutes les tables.
do $$
declare t text;
begin
  foreach t in array array[
    'categories','products','product_images','orders','order_items',
    'admin_users','product_reviews','promo_codes','blog_posts',
    'bundles','bundle_items','social_posts'
  ]
  loop
    execute format(
      'create policy hm_admin_all on public.%I for all to authenticated
         using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

-- Visiteurs : lecture du contenu public.
create policy hm_public_read on categories     for select using (true);
create policy hm_public_read on products       for select using (status = 'published');
create policy hm_public_read on product_images for select using (
  exists (select 1 from products p where p.id = product_id and p.status = 'published')
);
create policy hm_public_read on blog_posts     for select using (status = 'published');
create policy hm_public_read on bundles        for select using (status = 'published');
create policy hm_public_read on bundle_items   for select using (
  exists (select 1 from bundles b where b.id = bundle_id and b.status = 'published')
);
create policy hm_public_read on social_posts   for select using (true);
create policy hm_public_read on product_reviews for select using (approved = true);

-- Visiteurs : dépôt d'un avis (toujours en attente de validation).
create policy hm_public_insert on product_reviews for insert with check (
  approved = false
  and rating between 1 and 5
  and char_length(author_name) between 1 and 80
  and (comment is null or char_length(comment) <= 1000)
  and exists (select 1 from products p where p.id = product_id and p.status = 'published')
);

-- Un utilisateur connecté peut vérifier s'il est lui-même administrateur
-- (utilisé par la page de connexion et le proxy).
create policy hm_self_read on admin_users for select to authenticated using (id = auth.uid());

-- orders, order_items, promo_codes : AUCUN accès direct pour les visiteurs.


-- ------------------------------------------------------------
-- 5. Fonctions publiques
-- ------------------------------------------------------------

-- Supprime les fonctions qui permettaient à n'importe quel visiteur de
-- modifier le stock (decrease_/increase_product_stock), ainsi que
-- l'ancienne version de create_order (sans moyen de paiement).
do $$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and (p.proname in ('decrease_product_stock', 'increase_product_stock')
           or (p.proname = 'create_order' and p.pronargs <> 7))
  loop
    execute format('drop function %s', f.sig);
  end loop;
end $$;

-- Vérifie un code promo sans exposer la liste des codes.
create or replace function public.validate_promo(p_code text)
returns table (code text, discount_percent integer)
language sql
stable
security definer
set search_path = public
as $$
  select pc.code, pc.discount_percent
  from promo_codes pc
  where lower(pc.code) = lower(trim(p_code))
    and pc.active
    and (pc.expires_at is null or pc.expires_at > now())
  limit 1;
$$;


-- Crée une commande : prix relus dans la base, stock vérifié et retiré
-- en une seule opération (pas de survente, pas de prix modifiable).
-- p_items : [{"product_id": "...", "quantity": 2}, ...]
-- p_payment_method : mtn_momo | moov_money | celtiis_cash | cash
create or replace function public.create_order(
  p_name text,
  p_phone text,
  p_address text,
  p_notes text,
  p_items jsonb,
  p_promo_code text default null,
  p_payment_method text default 'cash'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_product record;
  v_qty integer;
  v_subtotal integer := 0;
  v_discount integer := 0;
  v_percent integer;
  v_code text;
  v_order orders%rowtype;
  v_lines jsonb := '[]'::jsonb;
  v_phone_key text := right(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'), 8);
begin
  if coalesce(trim(p_name), '') = '' or coalesce(trim(p_phone), '') = '' then
    raise exception 'missing_fields';
  end if;
  if char_length(p_name) > 120 or char_length(p_phone) > 30
     or char_length(coalesce(p_address, '')) > 300
     or char_length(coalesce(p_notes, '')) > 1000 then
    raise exception 'field_too_long';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'empty_cart';
  end if;
  if char_length(v_phone_key) < 8 then
    raise exception 'invalid_phone';
  end if;
  if coalesce(p_payment_method, '') not in ('mtn_momo', 'moov_money', 'celtiis_cash', 'cash') then
    raise exception 'invalid_payment_method';
  end if;

  -- Anti-spam : au plus 3 commandes non traitées par téléphone en 30 minutes,
  -- et 40 nouvelles commandes au total en 10 minutes (protège le stock
  -- contre quelqu'un qui passerait des centaines de fausses commandes).
  if (select count(*) from orders
      where status = 'new'
        and created_at > now() - interval '30 minutes'
        and right(regexp_replace(customer_phone, '\D', '', 'g'), 8) = v_phone_key) >= 3
     or (select count(*) from orders
         where created_at > now() - interval '10 minutes') >= 40 then
    raise exception 'too_many_orders';
  end if;

  -- Produits, prix et stock (lignes verrouillées pendant la commande).
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := (v_item->>'quantity')::integer;
    if v_qty is null or v_qty < 1 or v_qty > 999 then
      raise exception 'invalid_quantity';
    end if;

    select id, name, price, stock into v_product
    from products
    where id = (v_item->>'product_id')::uuid and status = 'published'
    for update;

    if not found then
      raise exception 'product_unavailable';
    end if;
    if v_product.stock < v_qty then
      raise exception 'insufficient_stock:%', v_product.name;
    end if;

    update products set stock = stock - v_qty, updated_at = now()
    where id = v_product.id;

    v_subtotal := v_subtotal + v_product.price * v_qty;
    v_lines := v_lines || jsonb_build_object(
      'product_id', v_product.id,
      'product_name', v_product.name,
      'quantity', v_qty,
      'price', v_product.price
    );
  end loop;

  -- Code promo (revérifié ici, quoi qu'affiche le navigateur).
  if coalesce(trim(p_promo_code), '') <> '' then
    select vp.code, vp.discount_percent into v_code, v_percent
    from public.validate_promo(p_promo_code) vp;
    if v_code is not null then
      v_discount := round(v_subtotal * v_percent / 100.0);
    end if;
  end if;

  insert into orders (customer_name, customer_phone, customer_address, notes,
                      total, promo_code, discount, payment_method)
  values (trim(p_name), trim(p_phone), nullif(trim(coalesce(p_address, '')), ''),
          nullif(trim(coalesce(p_notes, '')), ''),
          v_subtotal - v_discount, v_code, v_discount, p_payment_method)
  returning * into v_order;

  insert into order_items (order_id, product_id, product_name, quantity, price)
  select v_order.id, (l->>'product_id')::uuid, l->>'product_name',
         (l->>'quantity')::integer, (l->>'price')::integer
  from jsonb_array_elements(v_lines) l;

  return jsonb_build_object(
    'order_number', v_order.order_number,
    'subtotal', v_subtotal,
    'discount', v_discount,
    'total', v_order.total,
    'promo_code', v_code,
    'payment_method', p_payment_method,
    'items', v_lines
  );
end;
$$;


-- Suivi : une commande n'est visible qu'avec son numéro ET le téléphone.
create or replace function public.track_order(p_phone text, p_order_number bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'order_number', o.order_number,
    'status', o.status,
    'total', o.total,
    'payment_method', o.payment_method,
    'paid', o.paid,
    'created_at', o.created_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'product_name', i.product_name,
        'quantity', i.quantity,
        'price', i.price
      ) order by i.created_at)
      from order_items i where i.order_id = o.id
    ), '[]'::jsonb)
  )
  from orders o
  where o.order_number = p_order_number
    -- On compare les 8 derniers chiffres : « +229 01 97 11 22 33 »,
    -- « 0197112233 » et « 97 11 22 33 » désignent le même numéro.
    and char_length(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g')) >= 8
    and right(regexp_replace(o.customer_phone, '\D', '', 'g'), 8)
      = right(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'), 8)
  limit 1;
$$;


-- Commande annulée par l'admin : le stock est remis automatiquement.
create or replace function public.restock_cancelled_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'cancelled' and old.status is distinct from 'cancelled' then
    update products p
    set stock = p.stock + i.quantity
    from order_items i
    where i.order_id = new.id and i.product_id = p.id;
  elsif old.status = 'cancelled' and new.status is distinct from 'cancelled' then
    update products p
    set stock = greatest(p.stock - i.quantity, 0)
    from order_items i
    where i.order_id = new.id and i.product_id = p.id;
  end if;
  return new;
end;
$$;

drop trigger if exists orders_restock on orders;
create trigger orders_restock
  after update of status on orders
  for each row execute function public.restock_cancelled_order();


-- ------------------------------------------------------------
-- 6. Droits d'exécution
-- ------------------------------------------------------------
revoke all on function public.create_order(text, text, text, text, jsonb, text, text) from public;
revoke all on function public.track_order(text, bigint) from public;
revoke all on function public.validate_promo(text) from public;
revoke all on function public.restock_cancelled_order() from public;

grant execute on function public.create_order(text, text, text, text, jsonb, text, text) to anon, authenticated;
grant execute on function public.track_order(text, bigint) to anon, authenticated;
grant execute on function public.validate_promo(text) to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;
